name: Update Mizzou Weather
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install requests beautifulsoup4
      - run: python update_placefile.py
      - run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add mizzou_weather.txt
          git commit -m "Auto update" || echo "no changes"
          git push
